index.js

This only enables you to require page.js in a clean node environment without crashing. All I did is check for `window` availability safely. Since even Mocha tests are running with jsdom, I'm not entirely sure how to test this.
Partially resolves #191

Safer checking for window object to enable server-side use

---

package.json

Right now page.js is not included in the npm package, that seems like a mistake.
If you merge this pull request, could you also be so kind to release a new version to npm.

Include page.js in npm package

---

index.js

If page.js is loaded after the `load` event fires, the `onpopstate` function is never attached to the `popstate` event.
This tweak prevents that, but also prevents the hack which fixes #213 from working if page.js is loaded after the load event fires.
I think this is an acceptable compromise for now, because it allows #213 to remain fixed if page.js is loaded before the `load` event fires.
We can always replace this with something better if someone identifies a solution which fixes it in all cases.

Fix for post load event regression

---

page.js

I ran into a bug where the click event registered in page.js did not fire in firefox. I tried to pin it down, and I saw that the `window` object does not have a `click` event documented, but the `document` object has[1].
Changing the code solved my problem.
This PR changes the `eventlistener` for the `click` event from `window` to `document`.
[1]https://developer.mozilla.org/en-US/docs/Web/Events/click

use document event listener for click event instead of window

---

Readme.md

http://cdn.rawgit.com should be linked to version numbers, and never `master`. It will cache it once and never update again.

Readme: remove cdn url

---

History.md
test/tests.js

Fixed the only test which exercised a non-`'*'` wildcard route (which wasn't actually testing anything it was supposed to) and updated History.md

More prep for 1.6.4

---

index.js

This package is well written and works well with closure-compiler advanced optimizations. The only thing lacking for full support is a few changes to the JSDoc so that it is usable without warning.
Hopefully this can be merged as I'm using it in a project with Closure-compiler and would like to avoid a fork.
If you have style/formatting preferences, I'd be more than happy to tweak the JSDoc changes to be as close as possible to them.

Add type annotations for full closure-compiler advanced optimization support

---

index.js

PR #284 was made against page.js, not index.js, so they were overridden when doing `npm publish`.
https://github.com/visionmedia/page.js/commit/00899e6c0c0b7e45b1f1962709c58b91ceec9812#commitcomment-16690945

Reinstate shadow DOM fixes

---

.travis.yml

Travis recommends use container-based infrastructure over legacy one. All info at Travis Docs: [Migrating from legacy](http://docs.travis-ci.com/user/migrating-from-legacy/)

Migrate from Travis legacy to container-based infrastructure

---

index.js
page.js

TypeScript projects expect the module export to contain a `default`
property in order for imports to work:
```ts
import page from 'page';
```
This makes that work. In the future page.js will be an ES module so this
won't be necessary.
Fixes #365

Add a default export to work with TypeScript

---

index.js

Simple if clause to avoid use of `window.history` if the history object is not available. Allows for simple routing with node.js.

Small fix to prevent errors referencing `history` on node.js

---

Readme.md
index.js
test/tests.js

This is extremely useful to maintain developer sanity when using relative links.

Add page.strict() to control strict path matching.

---

.gitignore
.jshintrc
.travis.yml
index.js
package.json
test/support/jsdom.js
test/tests.js

This makes it possible to develop page.js using more recent Node
versions, while staying backwards compatible to 0.10 for CI purposes
mostly.
Closes #432

Allow development in more recent Node versions

---

index.js
page.js

**What it is:**
An improvement to onclick function, to correctly handle svg links too.
- without compromising non-svg links
- using and respecting the same checks, e.g. target and external checking
- no duplication of code, because the same lines are now compatible with svg and non-svg links
**Why it is needed:**
To make projects that use SVG links compatible with page.js
- SVG support is [a standard](http://caniuse.com/#feat=svg)
- Web and mobile projects with UI based on SVG are [awesome](http://slides.com/sarasoueidan/building-better-interfaces-with-svg)!

Correctly handle clicks from svg links

---

index.js
test/tests.js

This fixes #407. Previously sameOrigin() was returning false positives
due to depending on an indexOf() === 0. This uses the URL constructor
(falling back to an anchor) for better accuracy.

Prevent similar looking domains to trigger page callbacks

---

Makefile
index.js
test/support/jsdom.js
test/tests.js

This change improves support for using the file protocol with page.js.
Basically once you enable hashbang we treat the base as though it were
`/`. Fixes #209

Improve support for the file protocol

---

Readme.md

I expected page.js just using `encodeURIComponent` but stumbled over the special handling of plus signs. So I added a note accordingly.

Added clarification for decoded plus signs in urls

---

index.js
test/test-page.html
test/tests.js

This moves individual test to all run inside of iframes. This ensures
that there is some level of isolation for tests and that you can run
them in an actual browser and not just depend on jsdom.
This fixes #442
It also provides a new way to use an alternative to the main window by
passing the `window` option when starting page.
```js
page('/about', function(){
});
page({
window: myIframe.contentWindow
})
```
In the future (probably post-2.0) I want to make it possible to have
multiple Pages running at the same time, but for now this is what we'll
have.

Change test infrastructure to run inside of iframes

---

index.js
test/tests.js

As with the `URL()` constructor, we should leave the hash out of the
pathname. Fixes #375

Prevent hash from being part of the ctx.pathname

---

Readme.md

This adds a note about using page.js through a CDN, and the two CDNs we
support (unpkg and cdnjs).
Closes #120

Add a note about usage with a CDN

---

index.js
test/tests.js

Prevent going to the root when setting up the initial hashchange route

---

examples/partials/app.js

This updates the partials examples to work with any relative URL by
setting the base. So now it should work with any HTTP server. For #449

Update partials example to work with relative URL

---

index.js
test/test-page.html
test/tests.js

The onclick listening tries not to do anything when navigating to a hash
within the same page. However previously it did not take the `search`
into consideration so when you were on a page with a query param and
then navigating to the same path, without a query param, but with a
hash, it would cause a page navigation.
Fix is to include the search in this algorithm. Fixes #289

Ensure we are on the same page when exiting for hashes

---

index.js

In some bundle tools like browserify or webpack, when a global variable of process is parsed,
a polyfill of process will be included which is not exactly depended by this lib.

Fix redundancy of process dependence.

---

page.js

This change was introduced in #443. In some environments where `window` is not available it causes an attempt to access a property of `window.location`, which leads to an error.

Added a check for window existence before accessing location property.

---

index.js

I have noticed in some cases the `getBase` function is throwing an error because `pageWindow` is not properly checked.
So this PR is addressing this issue to resolve `Cannot read property 'location' of undefined` error.
It would be great if someone can do more investigation of why in some cases `pageWindow` become undefined in the first place.

Properly checking the object before pointing to an attribute

---

index.js

Before falling back to e.target from e.path use e.composedPath. This
allows the onclick handler to work for browsers using ShadyDom AND
Polymer 2.
IF I  use Polymer 2 and Page.js in FF or Safari then e.path doesn't exist because there is no ShadowDOM. e.target is the Top-most shadow DOM and is therefore not helpful.

Use event.composedPath as a fallback in onclick handler

---

Readme.md

The `unpkg` documentation was pointing users to the old npm package rather then the new one.

Update unpkg url to point at the correct version

---

Makefile
package.json
page.mjs

This adds an ES module, page.mjs that exports the `page` object as the
default export. Can be used like so:
```js
import page from '//unpkg.com/page/page.mjs';
page('/', show);
```
Eventually we might want to change the README to show this as the
primary usage.
Closes #499

Adds an ES module

---

.jshintrc
Readme.md
index.js
page.js
page.mjs
test/test-page.html
test/tests.js

This adds a new feature, `page.create()` that allows for there to be
multiple pages. Calling `page.create(options)` create a new page
function that behaves just like the global page. It contains its own
internal state, options, and event handlers. You can target the page to
another window, like an iframe or a popup, if you want.
```js
var newPage = page.create({
window: someIframe.contentWindow
});
```
The main reason for adding this feature was to clean up or testing
infrastructure. Numerous things had to be done in the past to make sure
each test was cleanly in isolation. That stuff is no longer necessary
now that we can just create a new page instance for each test.
Closes #13

Add page.create() to allow multiple pages

---

page.js

fixes #501 
Apparently the internal `_onpopstate` method isn't defined in environments where the `window` object doesn't exist such as test runners or Node.js. This PR adds a simple noop method to make sure it's defined.
I'm not aware of the internals of page.js and not sure if it causes any other side effects. I'm happy for feedback if this is actually a helpful fix.

make sure _onpopstate is defined in non-browser environments

---

Readme.md
index.js
page.js
page.mjs
test/tests.js

This adds `page.clickHandler`, which is the click handling function.
This is useful if you don't want page to handle all anchor links, but in
some scenarios you want to use its logic to dispatch events.
Closes #511

Export and document clickHandler

---

index.js
page.js
page.mjs

This was my bad in #514. I (wrongly) assumed the base path should be the `directory` path for `hashbang: true` and protocol `file:`, when it should be the actual full path of the page file (with i.e. `index.html`)

Fix wrong base for hashbang:true and protocol file:

---

index.js
page.js
page.mjs

Remove the `options` parameter from `page.create`/`createPage` (it wasn't used anyway) and also from the `Page` constructor together with the `configure` call there.
That ensures that the router is configured only once, with the user-supplied `options`, instead of being configured twice: first with default `options` in constructor, second time with user-supplied `options` in `page.start`.
Fixes a real-world issue where passing `{ click: false }` to `page.start` didn't prevent adding the global click handler to the document anyway, because the default value of the `click` option is `true`.
**How I tested this:**
Unit tests still pass both in Node and in browser.
I also tested the router in WordPress.com Calypso and it works as expected. The issues described in 
- …

Prevent duplicate event handler registration by configuring the router only once

---

index.js
page.js

We're using page.js for an internal project and ran across an issue with TypeScript.
From what I can figure out, rollup is not assigning globalPage as the default correctly. This works around that problem.

TypeScript: Missing default export

---

index.js

Seems there are no any reasons not to use `replaceState` with `file://` protocol

Using replaceState with file:// protocol

---

page.js

On ie11 loc.port returns an empty string if the port is 80.
This commit fixes the sameOrigin detection function for ie11.

ie11 sameOrigin detection fix

---

page.js
test/tests.js

In the case that all capture groups from a regex are optional and not supplied in the checked text; context.params[0] will be the "matched text" of the regex. Deleting property 0 from params before populating params prevents this.
https://github.com/visionmedia/page.js/issues/538

Remove Regex "matched text"

---

index.js
page.js

On IE11 if the port is 80 or 443, url.port is empty, so we have to check if port is 443 in case of https too.
Also, `===` got changed to `==`, because url.port is a string on some versions of IE11 (tested on IE11 on Windows 7).
(I really hope I don't have to support this browser for much longer)

fix ie11 sameOrigin check on https

---

package.json
test/index.html

Running `npm run serve` then visiting http://localhost:5000 results in all tests failing.
The problem is that `test/index.html` attempts to reference `../page.js`. This is not allowed by serve.  
However, there is already a symlink from the tests dir to page.js.  So, if we allow serve to follow symlinks then the problem is resolved and all the tests pass.

make the in browsers tests pass

---

index.html

Github pages syntax for exit is incorrect. Readme is fine, but GP is missing ctx and shows  next as the only parameter.

fix github pages exit code snippet

---

index.js
page.js
page.mjs
test/tests.js

`routePath` param added which contains the original string path provided in the page function.
```js
page('/profile/:userId', showUser);
page('/profile/5', showUser);
function showUser(ctx) {
if(ctx.routePath === '/profile/5')
document.write('Admin User');
else
document.write('User No: ', ctx.params.userId);
}
```
Co-Authored-By: Prabakaran Raja <prabakaranrvp@users.noreply.github.com>

Original path passed in the callback context

---

index.js
page.js
page.mjs
test/tests.js

`var _page` can be `page` (passed in as an argument) or `globalPage`. The opts are pulled from the first one instead of either one, this PR corrects that.

Fix _page typo in Route constructor
