visionmedia/page.js

- index.js
- page.js
- test/tests.js
> `ctx.params` became the object

- index.js
Deleted the old pull request because i screwed up the rebase :/
> Feature page.back

- index.js
Fixes issues #233 and #234, both of which involve the rules for ignoring clicks on links.
> Improved click handler behavior. Fixes #233 and #234.

- index.js
Hi,
The behavior on touch devices is different than on desktop. Like iPad does not trigger the click event at all. It would be nice to have the same behavior on all devices so I suggest this fix. Thanks for a great lib!
> Fixed touch support

- index.js
One commit version of this PR:
https://github.com/visionmedia/page.js/pull/232
> Fix for page.js on NW.js on Windows

- index.js
> Do not listen for the load event if the document is already loaded

- index.js
For isomorphic applications running on node, require('page') is throwing exception. This PR fixes the issue so that it works fine when requiring in node
> Fix requiring page.js on server side

- component.json
- package.json
- page.js
Pinging @shuvalov-anton per discussion in #315
Tests are passing: `108 passing (565ms)`
Thanks.
> New release to incorporate path-to-regexp 1.2.1

- page.js
tested with chrome, safari and firefox.
> use shadow dom when available

- Readme.md
marked the project as being no longer maintained and added a few alternatives
> No longer maintained

- Readme.md
Before:
After:
Just want to make the typography better :)
> Use SVG coverage badge

- Readme.md
implemenation → implementation
explaination → explanation
> Fix typos in Readme

- Readme.md
Reverts visionmedia/page.js#429
This repo is now maintained!
> Revert "No longer maintained"

- index.js
Previously submitted as https://github.com/visionmedia/page.js/pull/398
> Add duplicate exports to avoid aliases for Closure-compiler

- index.js
- test/tests.js
Previous pullrequest: https://github.com/visionmedia/page.js/pull/269
Fixes #268
> Set prevContext later to ensure that prevContext is accurate

- .jsbeautifyrc
beautification was removed in 4b081ed6d58a7862defc0a9eacbb974c3cab65c5
but the config file was forgotten.
> Remove beautify config file

- index.js
- test/tests.js
> Listen to popstate in browsers that do not support pushstate

- Readme.md
Glad to see this package alive again. I've added a section in the readme for tools/integrations available with other libraries and frameworks. I've built one for React earlier this month.
> Reference pagify-it for usage with React

- Makefile
- index.js
- package.json
- rollup.config.js
This switches to using rollup for the build. This fixes #444 among other
things.
> Switch to rollup for the build

- Readme.md
in the following section I replaced expensive with extensive for improved comprehension.
When working with the `pushState` API,
and page.js you may optionally provide
state objects available when the user navigates
the history.
For example if you had a photo application
and you performed a relatively extensive
search to populate a list of images,
normally when a user clicks "back" in
the browser the route would be invoked
and the query would be made yet-again.
An example implementation might look as follows:
> replaced expensive with extensive in the Readme.md

- package.json
> Upgrade the engine-dependencies version

- test/tests.js
E.g.:
```js
page('/async', function(ctx, next) {
setTimeout(function() {
next();
}, 10);
}
```
> Add tests for validating asynchronous callbacks.

- index.js
- page.js
- page.mjs
- test/demos/back-demo.html
When navigating to the current page, include the querystring as part of
the Context.
Fixes #495
> Fix querystring prop in context when navigating to the same page

- index.js
- page.js
- page.mjs
> make sure _onpopstate is defined in non-browser envs

- .travis.yml
- index.js
- page.js
- page.mjs
- test/tests.js
> Prevent default link behaviour when hashbang: true and protocol is file:

- Readme.md
See https://github.com/visionmedia/page.js/issues/534
> Remove pagify-it from readme as discussed

- index.js
- page.js
Get a fresh clone of master and run `npm run make` without making any changes and you get differences to the page.js file.  It looks like #535 and #539 made changes directly to the dest file.
The page.js file is changed in the PR because #535 required linting fixes.
> Sync and src dest files.
